export const socketAct = {
  CONNECTION: 'connection',
  CREATE_ROOM: 'create room',
  JOIN_ROOM: 'join the room',
  CONFIRM_STEPS: 'confirm steps',
  ADD_PARTICIPANT: 'add participant',
  LEAVE_GAME: 'leave game',
  CANCEL_GAME: 'cancel game',
  DISCONNECT: 'disconnect',
  GET_FIELDS: 'get fields',
  OPPONENT_FIELD: 'optional field',
  STEP: 'step',
  OPPONENTS_STEP: 'opponents step',
  SKIP_STEP: 'skip step',
  SKIP: 'skip',
  TIMER: 'timer',
  FIELDS_READY: 'fields ready',
  GAME_OVER: 'game over',
  GET_GAME_DATA: 'get game data',
  GET_RANDOM_SHIP_PLACEMENT: 'get random ship placement',
  GET_RATE: 'get rate',
  GET_CREATED_GAMES: 'get created games',
  GET_STARTED_GAME: 'get started games',
  GAME_CREATED: 'created game',
  GET_FIELDS_AND_STEPS: 'get fields and steps',
  GET_USERS_RATE: 'get users rate',
};
